backend:
    name: git-gateway
    branch: master # Branch to update
media_folder: assets/img/cms # Media files will be stored in the repo here
public_folder: /img/cms # The src attribute for uploaded media will begin with this
logo_url: /img/cms-logo.png # Logo shown on CMS login page
collections:
  - label: Home Page
    name: home-config
    description: Change the content on the home page
    create: false
    files:
      - label: Announcements
        name: announcements
        file: assets/home-config/announcements.json
        fields:
          - label: Announcements
            name: announcements
            widget: list
            hint: Let visitors know about special events, closures, etc.
            fields:
              - {label: Headline, name: headline, widget: string}
              - {label: Body, name: body, widget: text, required: false}
      - label: Carousel Photos
        name: carousel-photos
        file: assets/home-config/carousel.json
        fields:
          - label: Photos
            name: images
            widget: list
            hint: A set of photos to display at the top of the page
            fields:
              - {label: Accessibility Description, name: alt, widget: string, hint: Briefly describe what is in this photo}
              - {label: Photo, name: path, widget: image, allow_multiple: false, hint: Use photos that are at least 2000 pixels wide to ensure that they look good on any size screen}
      - label: Article
        name: article
        file: content/home.md
        fields:
          - {label: Article Content, name: body, widget: markdown, hint: Briefly introduce visitors to the business}
      - label: Skill Cards
        name: skill-cards
        file: assets/home-config/skill-cards.json
        fields:
          - label: Cards
            name: cards
            widget: list
            fields:
              - {label: Skill, name: word, widget: string}
              - {label: Icon, name: icon, widget: string, hint: "List of available icons: https://fontawesome.com/icons?s=solid"}
      - label: Class List
        name: class-list
        file: assets/home-config/class-cards.json
        fields:
          - label: Classes
            name: classes
            widget: list
            fields:
              - {label: Class Name, name: title, widget: string}
              - {label: Photo, name: img, widget: image, allow_multiple: false, required: false}
              - {label: Instructor Name, name: instructor, widget: string}
              - {label: Instructor Experience, name: experience, widget: string, required: false}
              - {label: Phone Number, name: phone, widget: string, required: false}
              - {label: Website URL, name: website, widget: string, required: false}
              - {label: Facebook Tag, name: facebook, widget: string, required: false}
              - {label: Instagram Tag, name: instagram, widget: string, required: false}
      - label: Hours
        name: hours
        file: assets/home-config/hours.json
        fields:
          - label: Rows
            name: rows
            widget: list
            fields:
              - {label: Day(s), name: days, widget: string}
              - {label: Times, name: times, widget: string}