backend:
    name: git-gateway
    branch: master # Branch to update
media_folder: assets/img/cms # Media files will be stored in the repo here
public_folder: /img/cms # The src attribute for uploaded media will begin with this
logo_url: /img/cms-logo.png # Logo shown on CMS login page
collections:
  - label: Home Page
    name: home-config
    description: Change the content on the home page
    create: false
    files:
      - label: Announcements
        name: announcements
        file: content/home-config/announcements.json
        fields:
          - label: Announcements
            label_singular: Announcement
            name: announcements
            widget: list
            hint: Let visitors know about special events, closures, etc.
            fields:
              - {label: Headline, name: headline, widget: string}
              - {label: Body, name: body, widget: text, required: false}
      - label: Carousel Photos
        name: carousel-photos
        file: content/home-config/carousel.json
        fields:
          - label: Photos
            label_singular: Photo
            name: images
            widget: list
            hint: A set of photos to display at the top of the page
            fields:
              - {label: Accessibility Description, name: alt, widget: string, hint: Briefly describe what is in this photo}
              - {label: Photo, name: path, widget: image, allow_multiple: false, hint: Use photos that are at least 2000 pixels wide to ensure that they look good on any size screen}
      - label: Article
        name: article
        file: content/home.md
        fields:
          - {label: Article Content, name: body, widget: markdown, hint: Briefly introduce visitors to the business}
      - label: Skill Cards
        name: skill-cards
        file: content/home-config/skill-cards.json
        fields:
          - label: Cards
            label_singular: Card
            name: cards
            widget: list
            fields:
              - {label: Skill, name: word, widget: string}
              - {label: Icon, name: icon, widget: string, hint: "List of available icons: https://fontawesome.com/icons?s=solid"}
      - label: Class List
        name: class-list
        file: content/home-config/class-list.json
        fields:
          - label: Classes
            label_singular: Class
            name: classes
            widget: list
            hint: Choose which classes are listed on the home page and in what order
            collapsed: false
            field:
              label: Class
              name: class
              widget: relation
              collection: classes
              value_field: "{{slug}}"
              search_fields: ["title"]
              display_fields: ["title"]
      - label: Hours
        name: hours
        file: content/home-config/hours.json
        fields:
          - label: Rows
            label_singular: Row
            name: rows
            widget: list
            fields:
              - {label: Day(s), name: days, widget: string}
              - {label: Times, name: times, widget: string}
  - label: Classes
    label_singular: Class
    name: classes
    description: Enter information to be displayed about the classes offered
    folder: content/classes
    extension: json
    create: true
    fields:
      - {label: Class Name, name: title, widget: string}
      - {label: Photo, name: img, widget: image, allow_multiple: false, required: false}
      - {label: Instructor Name, name: instructor, widget: string}
      - {label: Instructor Experience, name: experience, widget: string, required: false}
      - {label: Phone Number, name: phone, widget: string, required: false}
      - {label: Website URL, name: website, widget: string, required: false}
      - {label: Facebook Tag, name: facebook, widget: string, required: false}
      - {label: Instagram Tag, name: instagram, widget: string, required: false}