backend:
    name: git-gateway
    branch: master # Branch to update
media_folder: "static/img/cms" # Media files will be stored in the repo here
public_folder: "/img/cms" # The src attribute for uploaded media will begin with this
logo_url: "/img/cms-logo.png" # Logo shown on CMS login page
collections:
  - name: "home-config"
    label: "Home Configuration"
    description: "Settings to change the content on the home page"
    create: false
    files:
      - name: "skill-cards"
        label: "Skill Cards"
        file: "assets/home-config/skill-cards.json"
        fields:
          - label: Cards
            name: cards
            widget: list
            fields:
              - {label: Skill, name: word, widget: string}
              - {label: Icon, name: icon, widget: string}